services:
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9080:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://host.docker.internal:5432/sonar
      SONAR_JDBC_USERNAME: postgres
      SONAR_JDBC_PASSWORD: postgres
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
