# name: Build and Push to Docker Hub

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Detect changes in embedding
#         id: check_embedding
#         run: |
#           if git diff --quiet HEAD^ HEAD -- packages/ml/embedding; then
#             echo "changed=false" >> "$GITHUB_OUTPUT"
#           else
#             echo "changed=true" >> "$GITHUB_OUTPUT"
#           fi

#       - name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: ${{ vars.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_TOKEN }}

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3

#       - name: Build and push server image
#         uses: docker/build-push-action@v6
#         with:
#           context: .
#           file: ./packages/server/Dockerfile
#           push: true
#           tags: ${{ vars.DOCKER_USERNAME }}/server:latest

#       - name: Build and push embedding image
#         if: steps.check_embedding.outputs.changed == 'true'
#         uses: docker/build-push-action@v6
#         with:
#           context: ./packages/ml/embedding
#           dockerfile: Dockerfile
#           push: true
#           tags: ${{ vars.DOCKER_USERNAME }}/embedding:latest

name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: server
            context: .
            file: packages/server/Dockerfile
            image: ${{ vars.DOCKER_USERNAME }}/server

          - name: embedding
            context: packages/ml/embedding
            file: packages/ml/embedding/Dockerfile
            image: ${{ vars.DOCKER_USERNAME }}/embedding
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push ${{ matrix.service.name }} image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.service.context }}
          file: ${{ matrix.service.file }}
          push: true
          tags: ${{ matrix.service.image }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
