name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: server
            context: . # Root context to include package.json, etc.
            dockerfile: packages/server/Dockerfile
            image: ${{ vars.DOCKER_USERNAME }}/server
          - name: embedding
            context: . # Root context for pnpm workspace files
            dockerfile: packages/ml/embedding/Dockerfile # Correct path
            image: ${{ vars.DOCKER_USERNAME }}/embedding
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure full repo is checked out

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push ${{ matrix.service.name }} image
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.service.context }}
          dockerfile: ${{ matrix.service.dockerfile }}
          push: true
          tags: ${{ matrix.service.image }}:latest
          cache-from: type=gha # Cache for faster builds
          cache-to: type=gha,mode=max
