name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push server
        uses: docker/build-push-action@v6
        with:
          context: ./packages/server
          dockerfile: ./packages/server/Dockerfile
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/service1:latest

      - name: Build and push embedding
        uses: docker/build-push-action@v6
        with:
          context: ./packages/ml/embedding
          dockerfile: ./packages/ml/embedding/Dockerfile
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/service2:latest
